console.log("하하하");
console.log("하하하");
console.log("하하하");
console.log("하하하");
console.log("하하하");
console.log("하하하");
console.log("하하하");
console.log("해낼수 있는거니? 모르겠다...");
console.log("해낼수 있는거니? 모르겠다...");
console.log("해낼수 있는거니? 모르겠다...");
console.log("해낼수 있는거니? 모르겠다...");
console.log("해낼수 있는거니? 모르겠다...");
console.log("해낼수 있는거니? 모르겠다...");